# -*- coding: utf-8 -*-
"""football_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EM6L-QepfPTu7dAGMbVaJRqqMbbNWTB5
"""

#StatsBomb API library
!pip install statsbombpy

import pandas as pd
from statsbombpy import sb



#  Fetch all matches from the 2022 FIFA World Cup
matches = sb.matches(competition_id=43, season_id=106)

# Extract the event data for the World Cup Final
print("Argentina vs France")
events = sb.events(match_id=3869685)

print(f"Total events captured: {events.shape[0]}")
print(f"Total columns per event: {events.shape[1]}")

display(events.head(0))

print(events.columns)

import numpy as np

# Rebuilding pipeline using pre-flattened StatsBomb columns

core_columns = [
    'id', 'minute', 'second', 'type', 'team', 'player', 'position', 'location',
    'shot_outcome', 'shot_end_location',
    'pass_outcome', 'pass_recipient', 'pass_end_location',
    'goalkeeper_type', 'goalkeeper_outcome'
]

available_columns = [col for col in core_columns if col in events.columns]
df_clean = events[available_columns].copy()

# Split Starting 'location' into X and Y
if 'location' in df_clean.columns:
    df_clean['location_x'] = df_clean['location'].apply(lambda x: x[0] if isinstance(x, list) else np.nan)
    df_clean['location_y'] = df_clean['location'].apply(lambda x: x[1] if isinstance(x, list) else np.nan)
    df_clean = df_clean.drop(columns=['location'])

# Split 'shot_end_location' into X and Y
if 'shot_end_location' in df_clean.columns:
    df_clean['shot_end_x'] = df_clean['shot_end_location'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else np.nan)
    df_clean['shot_end_y'] = df_clean['shot_end_location'].apply(lambda x: x[1] if isinstance(x, list) and len(x) > 1 else np.nan)
    df_clean = df_clean.drop(columns=['shot_end_location'])

# Split 'pass_end_location' into X and Y
if 'pass_end_location' in df_clean.columns:
    df_clean['pass_end_x'] = df_clean['pass_end_location'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else np.nan)
    df_clean['pass_end_y'] = df_clean['pass_end_location'].apply(lambda x: x[1] if isinstance(x, list) and len(x) > 1 else np.nan)
    df_clean = df_clean.drop(columns=['pass_end_location'])

# Handle Pass Outcomes (StatsBomb leaves completed passes as NaN)
if 'pass_outcome' in df_clean.columns:
    df_clean['pass_outcome'] = df_clean['pass_outcome'].fillna('Completed')

# Clean up missing player data
if 'player' in df_clean.columns:
    df_clean = df_clean.dropna(subset=['player'])

display(df_clean.head())

"""Dimensionality Reduction: We dropped 90+ irrelevant columns, keeping only what we need to build our database and dashboard.

Data Unnesting: We applied a lambda function to safely extract the X and Y pitch coordinates so we can actually plot them on a map in Power BI later.

Data Quality Enforcement: We removed events that aren't tied to a specific player to ensure our player-level analytics are accurate.
"""

import sqlite3
from google.colab import files

# Building database in Colab local memory

# Save directly temporary storage
db_path = 'WorldCup_Football_Analytics.db'
conn = sqlite3.connect(db_path)

# Create the Dim_Players table
print("Dim_Players table")
dim_players = df_clean[['player', 'team']].dropna().drop_duplicates().reset_index(drop=True)
dim_players['player_id'] = dim_players.index + 1

# Fact_Events table
print("Fact_Events table")
fact_events = df_clean.merge(dim_players, on=['player', 'team'], how='left')
fact_events = fact_events.drop(columns=['player', 'team'])

# Load the data into the database
print("Writing data to SQLite...")
dim_players.to_sql('Dim_Players', conn, if_exists='replace', index=False)
fact_events.to_sql('Fact_Events', conn, if_exists='replace', index=False)

conn.close()

files.download(db_path)